# Workflow name
name: create-cloudformation-stack

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
jobs: # Jobs defined in the workflow
  create-stack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::947695616581:role/aws-service-role/sso.amazonaws.com/AWSServiceRoleForSSO
        aws-region: us-east-1

    - name: Create CloudFormation Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: udatest
        template: udatest.yml
        no-fail-on-empty-changeset: "1"